name: ecommerce_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  number_paginator: 0.4.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  http: ^1.2.2
  rxdart: ^0.28.0
  shared_preferences: ^2.1.1
  internet_connection_checker: ^1.0.0+1
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.0.2
  build_runner: ^2.1.2
  mockito: ^5.0.15
  mocktail: ^1.0.4
  
flutter:
  uses-material-design: true
  assets:
    - lib/core/assets/images/image.png
    - lib/core/assets/images/bag.jpg
  
